# Generated by Django 6.1.1 on 2026-09-05 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la filière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code (ex: INFO, GE)')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('niveau', models.CharField(default='Niveau 2', max_length=20, verbose_name='Niveau (ex: Niveau 2)')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='api.filiere', verbose_name='Filière associée')),
            ],
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'épreuve (ex: Examen Algorithmique S1)")),
                ('annee', models.IntegerField(verbose_name='Année académique (ex: 2025)')),
                ('type_ressource', models.CharField(choices=[('EXAMEN', 'Examen / CC'), ('TD', 'Travaux Dirigés (TD)'), ('COURS', 'Support de Cours')], default='EXAMEN', max_length=20)),
                ('fichier', models.FileField(upload_to='epreuves/', verbose_name='Fichier PDF')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('telechargements', models.PositiveIntegerField(default=0)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filiere', verbose_name='Filière')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matiere', verbose_name='Matière')),
            ],
        ),
    ]
