# Generated by Django 6.1.1 on 2026-09-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='filiere',
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='filiere',
            field=models.CharField(default='Génie Informatique', max_length=150),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='matiere',
            field=models.CharField(default='Algorithmique', max_length=150),
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='telechargements',
        ),
        migrations.RemoveField(
            model_name='epreuve',
            name='type_ressource',
        ),
        migrations.AddField(
            model_name='epreuve',
            name='niveau',
            field=models.CharField(default='Niveau 1', max_length=50),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='epreuves_pdfs/'),
        ),
        migrations.AddField(
            model_name='epreuve',
            name='type',
            field=models.CharField(default='Examen', max_length=50),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='annee',
            field=models.CharField(default='2025-2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='epreuve',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Filiere',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
